<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151222141110 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(80) NOT NULL, description VARCHAR(150) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage (persistence_object_identifier VARCHAR(40) NOT NULL, instagramcollection VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, uri VARCHAR(255) NOT NULL, INDEX IDX_A4BD82E25255FA0F (instagramcollection), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage ADD CONSTRAINT FK_A4BD82E25255FA0F FOREIGN KEY (instagramcollection) REFERENCES weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb (persistence_object_identifier)");
		$this->addSql("DROP TABLE typo3_neosdemotypo3org_domain_model_registration");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail CHANGE configuration configuration LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
		$this->addSql("DROP INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage DROP FOREIGN KEY FK_A4BD82E25255FA0F");
		$this->addSql("CREATE TABLE typo3_neosdemotypo3org_domain_model_registration (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, username VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, password VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, firstname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("DROP TABLE weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb");
		$this->addSql("DROP TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage");
		$this->addSql("ALTER TABLE typo3_media_domain_model_thumbnail CHANGE configuration configuration LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:json_array)'");
		$this->addSql("CREATE INDEX documentnodeidentifier ON typo3_neos_eventlog_domain_model_event (documentnodeidentifier)");
	}
}