<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160308104747 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage (persistence_object_identifier VARCHAR(40) NOT NULL, instagramcollection VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, uri VARCHAR(255) NOT NULL, INDEX IDX_A4BD82E25255FA0F (instagramcollection), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(80) NOT NULL, description VARCHAR(150) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage ADD CONSTRAINT FK_A4BD82E25255FA0F FOREIGN KEY (instagramcollection) REFERENCES weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage DROP FOREIGN KEY FK_A4BD82E25255FA0F");
		$this->addSql("DROP TABLE weissheiten_neos_instagrammedia_domain_model_instagramimage");
		$this->addSql("DROP TABLE weissheiten_neos_instagrammedia_domain_model_instagramcol_0cfdb");
	}
}