Neos:
  Flow:
    mvc:
      routes:
        Weissheiten.Neos.InstagramMedia:
          position: end
  Neos:
    modules:
      management:
        submodules:
          InstagramMedia:
            label: 'Instagram Media'
            controller: Weissheiten\Neos\InstagramMedia\Controller\CollectionController
            description: 'Instagram Collections'
            icon: 'fas fa-camera-retro'
            privilegeTarget: 'Weissheiten.Neos.InstagramMedia:CollectionControllerActions'
            additionalResources:
              javaScripts:
                - 'resource://Neos.Twitter.Bootstrap/Public/Libraries/jQuery/jquery-1.10.1.min.js'
                - 'resource://Neos.Twitter.Bootstrap/Public/2/js/bootstrap.min.js'
              styleSheets:
                - 'resource://Neos.Twitter.Bootstrap/Public/2/css/bootstrap.min.css'
                - 'resource://Neos.Media.Browser/Public/Libraries/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.css'
                - 'resource://Weissheiten.Neos.InstagramMedia/Public/CSS/InstagramMedia.css'
    fusion:
      autoInclude:
        Weissheiten.Neos.InstagramMedia: true
  Fusion:
    defaultContext:
      InstagramMediaLibrary: Weissheiten\Neos\InstagramMedia\TypoScript\Eel\Helper\InstagramMediaQuery
